[package]
name = "streambody"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["tracing"] }
futures-util = "0.3.28"
tokio = { version = "1.29.1", features = ["macros", "full"] }
tracing = "0.1.37"
